variables:
  POSTGRES_USER: ticktag
  POSTGRES_PASSWORD: ticktag
  POSTGRES_DB: ticktag

services:
  - postgres:9.6

server:
  image: maven:3.3.9-jdk-8
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - .mvn-cache
  script:
    - mkdir -p ~/.m2
    - rm -rf ~/.m2/repository/
    - mkdir -p .mvn-cache
    - ln -s "$CI_PROJECT_DIR/.mvn-cache" ~/.m2/repository
    - ls -ld ~/.m2/repository
    - mvn -B test -f backend/pom.xml

client:
  image: node:7.0
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - .npm-cache
    - frontend/node_modules
  script:
    - npm config set cache "$CI_PROJECT_DIR/.npm-cache"
    - npm config get cache
    - cd frontend
    - npm install
    - npm prune
    - npm run build
    - npm test
