variables:
  POSTGRES_USER: ticktag
  POSTGRES_PASSWORD: ticktag
  POSTGRES_DB: ticktag

services:
  - postgres:9.6

server:
  image: maven:3.3.9-jdk-8
  script:
    - apt-get update -y && apt-get install -y postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - mvn -B test -f backend/pom.xml

client:
  image: node:7.0
  script:
    - cd frontend
    - npm install
    - npm run build
    - npm test
