BEGIN;
UPDATE "ticket" SET "description_comment_id" = NULL;
UPDATE "ticket_tag_group" SET "default_ticket_tag_id" = NULL;
DELETE FROM "ticket_event_comment_text_changed" CASCADE;
DELETE FROM "ticket_event_current_estimated_time_changed" CASCADE;
DELETE FROM "ticket_event_due_date_changed" CASCADE;
DELETE FROM "ticket_event_initial_estimated_time_changed" CASCADE;
DELETE FROM "ticket_event_logged_time_added" CASCADE;
DELETE FROM "ticket_event_logged_time_removed" CASCADE;
DELETE FROM "ticket_event_mention_added" CASCADE;
DELETE FROM "ticket_event_parent_changed" CASCADE;
DELETE FROM "ticket_event_state_changed" CASCADE;
DELETE FROM "ticket_event_story_points_changed" CASCADE;
DELETE FROM "ticket_event_tag_added" CASCADE;
DELETE FROM "ticket_event_tag_removed" CASCADE;
DELETE FROM "ticket_event_title_changed" CASCADE;
DELETE FROM "ticket_event_user_added" CASCADE;
DELETE FROM "ticket_event_user_removed" CASCADE;
DELETE FROM "ticket_event" CASCADE;
DELETE FROM "logged_time" CASCADE;
DELETE FROM "time_category" CASCADE;
DELETE FROM "assigned_ticket_user" CASCADE;
DELETE FROM "assignment_tag" CASCADE;
DELETE FROM "assigned_ticket_tag" CASCADE;
DELETE FROM "comment" CASCADE;
DELETE FROM "ticket" CASCADE;
DELETE FROM "ticket_tag" CASCADE;
DELETE FROM "ticket_tag_group" CASCADE;
DELETE FROM "member" CASCADE;
DELETE FROM "project" CASCADE;
DELETE FROM "user_image" CASCADE;
DELETE FROM "user" CASCADE;
COMMIT;
