/* tslint:disable */
/**
 * TickTag REST API
 * TickTag issue tracking API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH }                                         from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class BoardApi {
    protected basePath = 'http://localhost:8080/';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }
	
	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1,T2>(objA: T1, objB: T2) {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                (<any>objA)[key] = (<any>objB)[key];
            }
        }
        return <T1&T2>objA;
    }

    /**
     * collectSubTickets
     * 
     * @param id id
     * @param tagId tagId
     */
    public collectSubTicketsUsingPUT(id: string, tagId: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.collectSubTicketsUsingPUTWithHttpInfo(id, tagId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getKanbanBoard
     * 
     * @param id id
     */
    public getKanbanBoardUsingGET(id: string, extraHttpRequestParams?: any): Observable<models.KanbanBoardResultJson> {
        return this.getKanbanBoardUsingGETWithHttpInfo(id, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * listKanbanBoards
     * 
     * @param projectId projectId
     */
    public listKanbanBoardsUsingGET(projectId: string, extraHttpRequestParams?: any): Observable<Array<models.KanbanBoardResultJson>> {
        return this.listKanbanBoardsUsingGETWithHttpInfo(projectId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * listKanbanColumns
     * 
     * @param id id
     * @param numbers numbers
     * @param title title
     * @param tags tags
     * @param users users
     * @param progressOne progressOne
     * @param progressTwo progressTwo
     * @param progressGreater progressGreater
     * @param dueDateOne dueDateOne
     * @param dueDateTwo dueDateTwo
     * @param dueDateGreater dueDateGreater
     * @param storyPointsOne storyPointsOne
     * @param storyPointsTwo storyPointsTwo
     * @param storyPointsGreater storyPointsGreater
     * @param open open
     */
    public listKanbanColumnsUsingGET(id: string, numbers?: Array<number>, title?: string, tags?: Array<string>, users?: Array<string>, progressOne?: number, progressTwo?: number, progressGreater?: boolean, dueDateOne?: number, dueDateTwo?: number, dueDateGreater?: boolean, storyPointsOne?: number, storyPointsTwo?: number, storyPointsGreater?: boolean, open?: boolean, extraHttpRequestParams?: any): Observable<Array<models.KanbanColumnResultJson>> {
        return this.listKanbanColumnsUsingGETWithHttpInfo(id, numbers, title, tags, users, progressOne, progressTwo, progressGreater, dueDateOne, dueDateTwo, dueDateGreater, storyPointsOne, storyPointsTwo, storyPointsGreater, open, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateKanbanBoards
     * 
     * @param id id
     * @param columns columns
     */
    public updateKanbanBoardsUsingPUT(id: string, columns: Array<models.UpdateKanbanColumnJson>, extraHttpRequestParams?: any): Observable<{}> {
        return this.updateKanbanBoardsUsingPUTWithHttpInfo(id, columns, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * collectSubTickets
     * 
     * @param id id
     * @param tagId tagId
     */
    public collectSubTicketsUsingPUTWithHttpInfo(id: string, tagId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/board/${id}/collect`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling collectSubTicketsUsingPUT.');
        }
        // verify required parameter 'tagId' is not null or undefined
        if (tagId === null || tagId === undefined) {
            throw new Error('Required parameter tagId was null or undefined when calling collectSubTicketsUsingPUT.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: tagId == null ? '' : JSON.stringify(tagId), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getKanbanBoard
     * 
     * @param id id
     */
    public getKanbanBoardUsingGETWithHttpInfo(id: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/board/${id}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getKanbanBoardUsingGET.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * listKanbanBoards
     * 
     * @param projectId projectId
     */
    public listKanbanBoardsUsingGETWithHttpInfo(projectId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/board/`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'projectId' is not null or undefined
        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling listKanbanBoardsUsingGET.');
        }
        if (projectId !== undefined) {
            queryParameters.set('projectId', <any>projectId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * listKanbanColumns
     * 
     * @param id id
     * @param numbers numbers
     * @param title title
     * @param tags tags
     * @param users users
     * @param progressOne progressOne
     * @param progressTwo progressTwo
     * @param progressGreater progressGreater
     * @param dueDateOne dueDateOne
     * @param dueDateTwo dueDateTwo
     * @param dueDateGreater dueDateGreater
     * @param storyPointsOne storyPointsOne
     * @param storyPointsTwo storyPointsTwo
     * @param storyPointsGreater storyPointsGreater
     * @param open open
     */
    public listKanbanColumnsUsingGETWithHttpInfo(id: string, numbers?: Array<number>, title?: string, tags?: Array<string>, users?: Array<string>, progressOne?: number, progressTwo?: number, progressGreater?: boolean, dueDateOne?: number, dueDateTwo?: number, dueDateGreater?: boolean, storyPointsOne?: number, storyPointsTwo?: number, storyPointsGreater?: boolean, open?: boolean, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/board/${id}/columns`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling listKanbanColumnsUsingGET.');
        }
        if (numbers !== undefined) {
            queryParameters.set('numbers', <any>numbers);
        }
        if (title !== undefined) {
            queryParameters.set('title', <any>title);
        }
        if (tags !== undefined) {
            queryParameters.set('tags', <any>tags);
        }
        if (users !== undefined) {
            queryParameters.set('users', <any>users);
        }
        if (progressOne !== undefined) {
            queryParameters.set('progressOne', <any>progressOne);
        }
        if (progressTwo !== undefined) {
            queryParameters.set('progressTwo', <any>progressTwo);
        }
        if (progressGreater !== undefined) {
            queryParameters.set('progressGreater', <any>progressGreater);
        }
        if (dueDateOne !== undefined) {
            queryParameters.set('dueDateOne', <any>dueDateOne);
        }
        if (dueDateTwo !== undefined) {
            queryParameters.set('dueDateTwo', <any>dueDateTwo);
        }
        if (dueDateGreater !== undefined) {
            queryParameters.set('dueDateGreater', <any>dueDateGreater);
        }
        if (storyPointsOne !== undefined) {
            queryParameters.set('storyPointsOne', <any>storyPointsOne);
        }
        if (storyPointsTwo !== undefined) {
            queryParameters.set('storyPointsTwo', <any>storyPointsTwo);
        }
        if (storyPointsGreater !== undefined) {
            queryParameters.set('storyPointsGreater', <any>storyPointsGreater);
        }
        if (open !== undefined) {
            queryParameters.set('open', <any>open);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateKanbanBoards
     * 
     * @param id id
     * @param columns columns
     */
    public updateKanbanBoardsUsingPUTWithHttpInfo(id: string, columns: Array<models.UpdateKanbanColumnJson>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/board/${id}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'id' is not null or undefined
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateKanbanBoardsUsingPUT.');
        }
        // verify required parameter 'columns' is not null or undefined
        if (columns === null || columns === undefined) {
            throw new Error('Required parameter columns was null or undefined when calling updateKanbanBoardsUsingPUT.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: columns == null ? '' : JSON.stringify(columns), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}

