/* tslint:disable */
/**
 * TickTag REST API
 * TickTag issue tracking API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH }                                         from '../variables';
import { Configuration }                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class LoggedTimeApi {
    protected basePath = 'http://localhost:8080/';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }
	
	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1,T2>(objA: T1, objB: T2) {
        for(let key in objB){
            if(objB.hasOwnProperty(key)){
                (<any>objA)[key] = (<any>objB)[key];
            }
        }
        return <T1&T2>objA;
    }

    /**
     * createLoggedTime
     * 
     * @param req req
     */
    public createLoggedTimeUsingPOST(req: models.CreateLoggedTimeJson, extraHttpRequestParams?: any): Observable<models.LoggedTimeResultJson> {
        return this.createLoggedTimeUsingPOSTWithHttpInfo(req, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * deleteLoggedTime
     * 
     * @param loggedTimeId loggedTimeId
     */
    public deleteLoggedTimeUsingDELETE(loggedTimeId: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.deleteLoggedTimeUsingDELETEWithHttpInfo(loggedTimeId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLoggedTimesForComment
     * 
     * @param commentId commentId
     */
    public getLoggedTimesForCommentUsingGET(commentId: string, extraHttpRequestParams?: any): Observable<Array<models.LoggedTimeResultJson>> {
        return this.getLoggedTimesForCommentUsingGETWithHttpInfo(commentId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLoggedTimesForId
     * 
     * @param loggTimeId loggTimeId
     */
    public getLoggedTimesForIdUsingGET(loggTimeId: string, extraHttpRequestParams?: any): Observable<models.LoggedTimeResultJson> {
        return this.getLoggedTimesForIdUsingGETWithHttpInfo(loggTimeId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLoggedTimesForProjectAndUserAndCategory
     * 
     * @param projectId projectId
     * @param userId userId
     * @param categoryId categoryId
     */
    public getLoggedTimesForProjectAndUserAndCategoryUsingGET(projectId?: string, userId?: string, categoryId?: string, extraHttpRequestParams?: any): Observable<Array<models.LoggedTimeResultJson>> {
        return this.getLoggedTimesForProjectAndUserAndCategoryUsingGETWithHttpInfo(projectId, userId, categoryId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateLoggedTime
     * 
     * @param req req
     * @param loggedTimeId loggedTimeId
     */
    public updateLoggedTimeUsingPUT(req: models.UpdateLoggedTimeJson, loggedTimeId: string, extraHttpRequestParams?: any): Observable<models.LoggedTimeResultJson> {
        return this.updateLoggedTimeUsingPUTWithHttpInfo(req, loggedTimeId, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * createLoggedTime
     * 
     * @param req req
     */
    public createLoggedTimeUsingPOSTWithHttpInfo(req: models.CreateLoggedTimeJson, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'req' is not null or undefined
        if (req === null || req === undefined) {
            throw new Error('Required parameter req was null or undefined when calling createLoggedTimeUsingPOST.');
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: req == null ? '' : JSON.stringify(req), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * deleteLoggedTime
     * 
     * @param loggedTimeId loggedTimeId
     */
    public deleteLoggedTimeUsingDELETEWithHttpInfo(loggedTimeId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time/${loggedTimeId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'loggedTimeId' is not null or undefined
        if (loggedTimeId === null || loggedTimeId === undefined) {
            throw new Error('Required parameter loggedTimeId was null or undefined when calling deleteLoggedTimeUsingDELETE.');
        }
        if (loggedTimeId !== undefined) {
            queryParameters.set('loggedTimeId', <any>loggedTimeId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getLoggedTimesForComment
     * 
     * @param commentId commentId
     */
    public getLoggedTimesForCommentUsingGETWithHttpInfo(commentId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'commentId' is not null or undefined
        if (commentId === null || commentId === undefined) {
            throw new Error('Required parameter commentId was null or undefined when calling getLoggedTimesForCommentUsingGET.');
        }
        if (commentId !== undefined) {
            queryParameters.set('commentId', <any>commentId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getLoggedTimesForId
     * 
     * @param loggTimeId loggTimeId
     */
    public getLoggedTimesForIdUsingGETWithHttpInfo(loggTimeId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time/${loggTimeId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'loggTimeId' is not null or undefined
        if (loggTimeId === null || loggTimeId === undefined) {
            throw new Error('Required parameter loggTimeId was null or undefined when calling getLoggedTimesForIdUsingGET.');
        }
        if (loggTimeId !== undefined) {
            queryParameters.set('loggTimeId', <any>loggTimeId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getLoggedTimesForProjectAndUserAndCategory
     * 
     * @param projectId projectId
     * @param userId userId
     * @param categoryId categoryId
     */
    public getLoggedTimesForProjectAndUserAndCategoryUsingGETWithHttpInfo(projectId?: string, userId?: string, categoryId?: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time/search`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (projectId !== undefined) {
            queryParameters.set('projectId', <any>projectId);
        }
        if (userId !== undefined) {
            queryParameters.set('userId', <any>userId);
        }
        if (categoryId !== undefined) {
            queryParameters.set('categoryId', <any>categoryId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            



        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateLoggedTime
     * 
     * @param req req
     * @param loggedTimeId loggedTimeId
     */
    public updateLoggedTimeUsingPUTWithHttpInfo(req: models.UpdateLoggedTimeJson, loggedTimeId: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/logged_time/${loggedTimeId}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'req' is not null or undefined
        if (req === null || req === undefined) {
            throw new Error('Required parameter req was null or undefined when calling updateLoggedTimeUsingPUT.');
        }
        // verify required parameter 'loggedTimeId' is not null or undefined
        if (loggedTimeId === null || loggedTimeId === undefined) {
            throw new Error('Required parameter loggedTimeId was null or undefined when calling updateLoggedTimeUsingPUT.');
        }
        if (loggedTimeId !== undefined) {
            queryParameters.set('loggedTimeId', <any>loggedTimeId);
        }


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];
        
            

        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: req == null ? '' : JSON.stringify(req), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });
        
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}

