BEGIN;

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "project" CASCADE;
DROP TABLE IF EXISTS "member" CASCADE;
DROP TABLE IF EXISTS "ticket" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "ticket_tag" CASCADE;
DROP TABLE IF EXISTS "ticket_tag_group" CASCADE;
DROP TABLE IF EXISTS "assignment_tag" CASCADE;
DROP TABLE IF EXISTS "time_category" CASCADE;
DROP TABLE IF EXISTS "assigned_ticket_tag" CASCADE;
DROP TABLE IF EXISTS "assigned_ticket_user" CASCADE;
DROP TABLE IF EXISTS "logged_time" CASCADE;
DROP TABLE IF EXISTS "mentioned_ticket" CASCADE;
DROP TABLE IF EXISTS "ticket_event" CASCADE;
DROP TABLE IF EXISTS "ticket_event_parent_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_title_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_state_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_story_points_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_initial_estimated_time_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_current_estimated_time_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_due_date_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_comment_text_changed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_tag_added" CASCADE;
DROP TABLE IF EXISTS "ticket_event_tag_removed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_user_added" CASCADE;
DROP TABLE IF EXISTS "ticket_event_user_removed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_mention_added" CASCADE;
DROP TABLE IF EXISTS "ticket_event_mention_removed" CASCADE;
DROP TABLE IF EXISTS "ticket_event_logged_time_added" CASCADE;
DROP TABLE IF EXISTS "ticket_event_logged_time_removed" CASCADE;
DROP TABLE IF EXISTS "kanban_cell" CASCADE;
COMMIT;
